driver:
  name: vagrant
  forward_agent: true
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/chef-marketplace']

provisioner:
  require_chef_omnibus: 12.1.1

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-10.04
    run_list: apt::default
  - name: centos-5.10
    run_list:  yum-epel::default
  - name: centos-6.5
    run_list:  yum-epel::default
  - name: centos-7.0
    run_list:  yum-epel::default

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/chef-marketplace
        install_dir: /opt
