AllCops:
  Exclude:
    - '**/bin/*'
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 50
Style/GuardClause:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FileName:
  Enabled: false
