AllCops:
  Exclude:
    - '**/bin/*'
    - 'Guardfile'
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 200
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Max: 40
Style/GuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FileName:
  Enabled: false
