---
version: '2'
# We're going to create and use our own network because the default docker
# network uses a 16 bit netmask that overlaps with our internal VPN network.
# I'm not sure why the default network needs 65k addresses, but alas, we'll
# go with our own class C because it won't overlap and we'll be able to hit the
# internal artifactory to download packages from the development channels.
networks:
  marketplace:
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1

services:
  chef-client-test:
    extends:
      file: docker-compose-services.yml
      service: chef-client-test
    networks:
      marketplace:
        ipv4_address: 172.16.239.5
        aliases:
          - chef-client.test
    links:
      - automate:automate
    depends_on:
      - automate
  automate:
    extends:
      file: docker-compose-services.yml
      service: automate
    networks:
      marketplace:
        ipv4_address: 172.16.239.3
        aliases:
          - automate-marketplace.test
    links:
      - ec2-metadata:ec2-metadata
  ec2-metadata:
    extends:
      file: docker-compose-services.yml
      service: ec2-metadata
    networks:
      marketplace:
        ipv4_address: 172.16.239.4
        aliases:
          - ec2-metadata.test
