development:
  biscotti:
    message: 'Please enter the Instance ID continue to the web interface'
    token: '12345'
    uuid_type: 'Instance ID'
    uuid: 'i-1234abcd'

production:
 biscotti:
    message: 'Please enter the Instance ID continue to the web interface'
    token: '12345'
    uuid_type: 'Instance ID'
    uuid: 'i-1234abcd'
