---
provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: vagrant-centos-6.6
    driver_plugin: vagrant
    driver_config:
      box: opscode-centos-6.6
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
        - ["forwarded_port", {guest: 8443, host: 8843, auto_correct: true}]
      customize:
        cpus: 2
        memory: 4096
  - name: vagrant-rhel-7.1
    driver_plugin: vagrant
    driver_config:
      box: opscode-rhel-7.1
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
        - ["forwarded_port", {guest: 8443, host: 8843, auto_correct: true}]
      customize:
        cpus: 2
        memory: 4096
  - name: vagrant-ubuntu-14.04
    driver_plugin: vagrant
    driver_config:
      box: opscode-ubuntu-14.04
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
        - ["forwarded_port", {guest: 8443, host: 8843, auto_correct: true}]
      customize:
        cpus: 2
        memory: 4096

suites:
  - name: server-aws
    run_list: chef-marketplace::default
    attributes:
      chef-marketplace:
        role: server
        platform: aws
        user: ec2-user
        documentation:
          url: https://docs.chef.io/aws_marketplace.html
        support:
          email: aws@chef.io
  - name: analytics-aws
    run_list: chef-marketplace::default
    attributes:
      chef-marketplace:
        role: analytics
        platform: aws
        user: ec2-user
        documentation:
          url: https://docs.chef.io/aws_marketplace.html
        support:
          email: aws@chef.io
  - name: aio-aws
    run_list: chef-marketplace::default
    attributes:
      chef-marketplace:
        role: aio
        platform: aws
        user: ec2-user
        documentation:
          url: https://docs.chef.io/aws_marketplace.html
        support:
          email: aws@chef.io
    driver:
      network:
        - ["public_network", {ip: 10.10.0.88, bridge: "en3: Thunderbolt Ethernet"}]
  - name: compliance-aws
    run_list: chef-marketplace::default
    attributes:
      chef-marketplace:
        role: compliance
        platform: aws
        user: ec2-user
        documentation:
          url: https://docs.chef.io/aws_marketplace.html
        support:
          email: aws@chef.io
    driver:
      network:
        - ["public_network", {ip: 10.10.0.88, bridge: "en3: Thunderbolt Ethernet"}]
  - name: server-openstack
    run_list: chef-marketplace::default
    attributes:
      chef-marketplace:
        role: server
        platform: openstack
        user: openstack-user
        documentation:
          url: https://docs.chef.io/openstack_marketplace.html
        support:
          email: openstack@chef.io
  - name: analytics-openstack
    run_list: chef-marketplace::default
    attributes:
      chef-marketplace:
        role: analytics
        platform: openstack
        user: openstack-user
        documentation:
          url: https://docs.chef.io/openstack_marketplace.html
        support:
          email: openstack@chef.io
  - name: aio-openstack
    run_list: chef-marketplace::default
    attributes:
      chef-marketplace:
        role: aio
        platform: openstack
        user: openstack-user
        documentation:
          url: https://docs.chef.io/openstack_marketplace.html
        support:
          email: openstack@chef.io
    driver:
      network:
        - ["public_network", {ip: 10.10.0.88, bridge: "en3: Thunderbolt Ethernet"}]
