---
provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: vagrant-centos-6.6
    driver_plugin: vagrant
    driver_config:
      box: opscode-centos-6.6
      network:
        - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
      customize:
        cpus: 2
        memory: 4096

suites:
  - name: server
    run_list: chef-marketplace::default
    attributes:
      chef-marketplace:
        role: 'server'
  - name: analytics
    run_list: test::analytics
    attributes:
      chef-marketplace:
        role: 'analytics'
